language: java
sudo: false
dist: trusty
jdk: oraclejdk8

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.html)|^(LICENSE.txt)'
      then
        echo "Simple documentation update, skipping CI"
        exit
      fi

script:
- java -version
- ./gradlew dokka distZip

cache:
  directories:
    - '.$HOME/.gradle'
    - '.gradle'
