language: java
sudo: false
dist: trusty
install: true

before_script:
- unset -v _JAVA_OPTIONS
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
  - stage: 🚀 Graal
    env: JDK=graalvm-ce-19.2.0.1
    script: source install-jdk.sh --url https://github.com/oracle/graal/releases/download/vm-19.2.0.1/graalvm-ce-linux-amd64-19.2.0.1.tar.gz

install:
  - ./gradlew build

after_script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version

cache:
  directories:
    - '.$HOME/.gradle'
    - '.gradle'
